# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IMGWidget(object):
    def setupUi(self, IMGWidget):
        IMGWidget.setObjectName("IMGWidget")
        IMGWidget.resize(940, 622)
        self.gridLayout = QtWidgets.QGridLayout(IMGWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(IMGWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tw_images = QtWidgets.QTableWidget(self.tab)
        self.tw_images.setMinimumSize(QtCore.QSize(740, 100))
        self.tw_images.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_images.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_images.setObjectName("tw_images")
        self.tw_images.setColumnCount(14)
        self.tw_images.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(13, item)
        self.tw_images.horizontalHeader().setDefaultSectionSize(80)
        self.tw_images.verticalHeader().setVisible(False)
        self.tw_images.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_8.addWidget(self.tw_images, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setContentsMargins(12, -1, 12, 12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tw_dds_images = QtWidgets.QTableWidget(self.tab_2)
        self.tw_dds_images.setMinimumSize(QtCore.QSize(320, 0))
        self.tw_dds_images.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_dds_images.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_dds_images.setObjectName("tw_dds_images")
        self.tw_dds_images.setColumnCount(5)
        self.tw_dds_images.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(4, item)
        self.tw_dds_images.horizontalHeader().setDefaultSectionSize(80)
        self.tw_dds_images.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_7.addWidget(self.tw_dds_images, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(IMGWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 736, 337))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.w_draw = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_draw.sizePolicy().hasHeightForWidth())
        self.w_draw.setSizePolicy(sizePolicy)
        self.w_draw.setObjectName("w_draw")
        self.gridLayout_5.addWidget(self.w_draw, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(IMGWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tw_color_boards = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_color_boards.sizePolicy().hasHeightForWidth())
        self.tw_color_boards.setSizePolicy(sizePolicy)
        self.tw_color_boards.setMinimumSize(QtCore.QSize(100, 0))
        self.tw_color_boards.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_color_boards.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_color_boards.setObjectName("tw_color_boards")
        self.tw_color_boards.setColumnCount(1)
        self.tw_color_boards.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_color_boards.setHorizontalHeaderItem(0, item)
        self.tw_color_boards.horizontalHeader().setDefaultSectionSize(80)
        self.gridLayout_3.addWidget(self.tw_color_boards, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)

        self.retranslateUi(IMGWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IMGWidget)

    def retranslateUi(self, IMGWidget):
        _translate = QtCore.QCoreApplication.translate
        IMGWidget.setWindowTitle(_translate("IMGWidget", "IMG_Widget"))
        item = self.tw_images.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))
        item = self.tw_images.horizontalHeaderItem(1)
        item.setText(_translate("IMGWidget", "图像格式"))
        item = self.tw_images.horizontalHeaderItem(2)
        item.setText(_translate("IMGWidget", "索引（链接）"))
        item = self.tw_images.horizontalHeaderItem(3)
        item.setText(_translate("IMGWidget", "扩展格式"))
        item = self.tw_images.horizontalHeaderItem(4)
        item.setText(_translate("IMGWidget", "宽度"))
        item = self.tw_images.horizontalHeaderItem(5)
        item.setText(_translate("IMGWidget", "高度"))
        item = self.tw_images.horizontalHeaderItem(6)
        item.setText(_translate("IMGWidget", "数据大小"))
        item = self.tw_images.horizontalHeaderItem(7)
        item.setText(_translate("IMGWidget", "画布宽度"))
        item = self.tw_images.horizontalHeaderItem(8)
        item.setText(_translate("IMGWidget", "画布高度"))
        item = self.tw_images.horizontalHeaderItem(9)
        item.setText(_translate("IMGWidget", "索引（dds）"))
        item = self.tw_images.horizontalHeaderItem(10)
        item.setText(_translate("IMGWidget", "左边"))
        item = self.tw_images.horizontalHeaderItem(11)
        item.setText(_translate("IMGWidget", "顶边"))
        item = self.tw_images.horizontalHeaderItem(12)
        item.setText(_translate("IMGWidget", "右边"))
        item = self.tw_images.horizontalHeaderItem(13)
        item.setText(_translate("IMGWidget", "底边"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("IMGWidget", "图像列表"))
        item = self.tw_dds_images.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))
        item = self.tw_dds_images.horizontalHeaderItem(1)
        item.setText(_translate("IMGWidget", "数据大小"))
        item = self.tw_dds_images.horizontalHeaderItem(2)
        item.setText(_translate("IMGWidget", "原始大小"))
        item = self.tw_dds_images.horizontalHeaderItem(3)
        item.setText(_translate("IMGWidget", "宽度"))
        item = self.tw_dds_images.horizontalHeaderItem(4)
        item.setText(_translate("IMGWidget", "高度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("IMGWidget", "图像列表（dds）"))
        self.groupBox_4.setTitle(_translate("IMGWidget", "显示区域"))
        self.groupBox_3.setTitle(_translate("IMGWidget", "色板列表"))
        item = self.tw_color_boards.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))

