# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IMGWidget(object):
    def setupUi(self, IMGWidget):
        IMGWidget.setObjectName("IMGWidget")
        IMGWidget.resize(874, 600)
        self.gridLayout = QtWidgets.QGridLayout(IMGWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(IMGWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tw_color_boards = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_color_boards.sizePolicy().hasHeightForWidth())
        self.tw_color_boards.setSizePolicy(sizePolicy)
        self.tw_color_boards.setMinimumSize(QtCore.QSize(100, 0))
        self.tw_color_boards.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_color_boards.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_color_boards.setObjectName("tw_color_boards")
        self.tw_color_boards.setColumnCount(2)
        self.tw_color_boards.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_color_boards.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_color_boards.setHorizontalHeaderItem(1, item)
        self.tw_color_boards.horizontalHeader().setDefaultSectionSize(80)
        self.tw_color_boards.horizontalHeader().setStretchLastSection(True)
        self.tw_color_boards.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tw_color_boards, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(IMGWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tw_dds_images = QtWidgets.QTableWidget(self.groupBox_2)
        self.tw_dds_images.setMinimumSize(QtCore.QSize(340, 0))
        self.tw_dds_images.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_dds_images.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_dds_images.setObjectName("tw_dds_images")
        self.tw_dds_images.setColumnCount(4)
        self.tw_dds_images.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_dds_images.setHorizontalHeaderItem(3, item)
        self.tw_dds_images.horizontalHeader().setDefaultSectionSize(80)
        self.tw_dds_images.horizontalHeader().setStretchLastSection(True)
        self.tw_dds_images.verticalHeader().setVisible(False)
        self.tw_dds_images.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_7.addWidget(self.tw_dds_images, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(IMGWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tw_info = QtWidgets.QTableWidget(self.groupBox_4)
        self.tw_info.setObjectName("tw_info")
        self.tw_info.setColumnCount(1)
        self.tw_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_info.setHorizontalHeaderItem(0, item)
        self.tw_info.horizontalHeader().setVisible(False)
        self.tw_info.horizontalHeader().setStretchLastSection(True)
        self.tw_info.verticalHeader().setVisible(True)
        self.gridLayout_2.addWidget(self.tw_info, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(IMGWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tw_images = QtWidgets.QTableWidget(self.groupBox)
        self.tw_images.setMinimumSize(QtCore.QSize(820, 100))
        self.tw_images.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw_images.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw_images.setObjectName("tw_images")
        self.tw_images.setColumnCount(10)
        self.tw_images.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_images.setHorizontalHeaderItem(9, item)
        self.tw_images.horizontalHeader().setDefaultSectionSize(80)
        self.tw_images.horizontalHeader().setStretchLastSection(True)
        self.tw_images.verticalHeader().setVisible(False)
        self.tw_images.verticalHeader().setDefaultSectionSize(24)
        self.gridLayout_6.addWidget(self.tw_images, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)

        self.retranslateUi(IMGWidget)
        QtCore.QMetaObject.connectSlotsByName(IMGWidget)

    def retranslateUi(self, IMGWidget):
        _translate = QtCore.QCoreApplication.translate
        IMGWidget.setWindowTitle(_translate("IMGWidget", "IMG_Widget"))
        self.groupBox_3.setTitle(_translate("IMGWidget", "(v6)调色板列表"))
        item = self.tw_color_boards.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))
        item = self.tw_color_boards.horizontalHeaderItem(1)
        item.setText(_translate("IMGWidget", "颜色数量"))
        self.groupBox_2.setTitle(_translate("IMGWidget", "(v5)图像列表（dds）"))
        item = self.tw_dds_images.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))
        item = self.tw_dds_images.horizontalHeaderItem(1)
        item.setText(_translate("IMGWidget", "数据大小"))
        item = self.tw_dds_images.horizontalHeaderItem(2)
        item.setText(_translate("IMGWidget", "原始大小"))
        item = self.tw_dds_images.horizontalHeaderItem(3)
        item.setText(_translate("IMGWidget", "尺寸"))
        self.groupBox_4.setTitle(_translate("IMGWidget", "IMG信息"))
        item = self.tw_info.verticalHeaderItem(0)
        item.setText(_translate("IMGWidget", "版本"))
        item = self.tw_info.verticalHeaderItem(1)
        item.setText(_translate("IMGWidget", "图像数量"))
        item = self.tw_info.verticalHeaderItem(2)
        item.setText(_translate("IMGWidget", "(v4)颜色数量"))
        item = self.tw_info.verticalHeaderItem(3)
        item.setText(_translate("IMGWidget", "(v5)图像数量（dds）"))
        item = self.tw_info.verticalHeaderItem(4)
        item.setText(_translate("IMGWidget", "(v6)调色板数量"))
        item = self.tw_info.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "值"))
        self.groupBox.setTitle(_translate("IMGWidget", "图像列表"))
        item = self.tw_images.horizontalHeaderItem(0)
        item.setText(_translate("IMGWidget", "索引"))
        item = self.tw_images.horizontalHeaderItem(1)
        item.setText(_translate("IMGWidget", "图像格式"))
        item = self.tw_images.horizontalHeaderItem(2)
        item.setText(_translate("IMGWidget", "索引（链接）"))
        item = self.tw_images.horizontalHeaderItem(3)
        item.setText(_translate("IMGWidget", "扩展格式"))
        item = self.tw_images.horizontalHeaderItem(4)
        item.setText(_translate("IMGWidget", "坐标"))
        item = self.tw_images.horizontalHeaderItem(5)
        item.setText(_translate("IMGWidget", "尺寸"))
        item = self.tw_images.horizontalHeaderItem(6)
        item.setText(_translate("IMGWidget", "画布尺寸"))
        item = self.tw_images.horizontalHeaderItem(7)
        item.setText(_translate("IMGWidget", "数据大小"))
        item = self.tw_images.horizontalHeaderItem(8)
        item.setText(_translate("IMGWidget", "索引（dds）"))
        item = self.tw_images.horizontalHeaderItem(9)
        item.setText(_translate("IMGWidget", "边距"))

