# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_content = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_content.setObjectName("tw_content")
        self.gridLayout.addWidget(self.tw_content, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.m_app = QtWidgets.QMenu(self.menubar)
        self.m_app.setObjectName("m_app")
        self.m_npk = QtWidgets.QMenu(self.menubar)
        self.m_npk.setObjectName("m_npk")
        self.menuSound = QtWidgets.QMenu(self.m_npk)
        self.menuSound.setObjectName("menuSound")
        self.m_img = QtWidgets.QMenu(self.menubar)
        self.m_img.setObjectName("m_img")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.a_open = QtWidgets.QAction(MainWindow)
        self.a_open.setObjectName("a_open")
        self.a_close = QtWidgets.QAction(MainWindow)
        self.a_close.setObjectName("a_close")
        self.a_insert_img = QtWidgets.QAction(MainWindow)
        self.a_insert_img.setObjectName("a_insert_img")
        self.a_replace_img = QtWidgets.QAction(MainWindow)
        self.a_replace_img.setObjectName("a_replace_img")
        self.a_remove_img = QtWidgets.QAction(MainWindow)
        self.a_remove_img.setObjectName("a_remove_img")
        self.a_insert_npk = QtWidgets.QAction(MainWindow)
        self.a_insert_npk.setObjectName("a_insert_npk")
        self.a_replace_npk = QtWidgets.QAction(MainWindow)
        self.a_replace_npk.setObjectName("a_replace_npk")
        self.a_remove_npk = QtWidgets.QAction(MainWindow)
        self.a_remove_npk.setObjectName("a_remove_npk")
        self.a_play = QtWidgets.QAction(MainWindow)
        self.a_play.setObjectName("a_play")
        self.a_pause = QtWidgets.QAction(MainWindow)
        self.a_pause.setObjectName("a_pause")
        self.a_stop = QtWidgets.QAction(MainWindow)
        self.a_stop.setObjectName("a_stop")
        self.a_loop = QtWidgets.QAction(MainWindow)
        self.a_loop.setCheckable(True)
        self.a_loop.setObjectName("a_loop")
        self.a_load_img = QtWidgets.QAction(MainWindow)
        self.a_load_img.setObjectName("a_load_img")
        self.m_app.addAction(self.a_open)
        self.m_app.addSeparator()
        self.m_app.addAction(self.a_close)
        self.menuSound.addAction(self.a_play)
        self.menuSound.addAction(self.a_pause)
        self.menuSound.addAction(self.a_stop)
        self.menuSound.addSeparator()
        self.menuSound.addAction(self.a_loop)
        self.m_npk.addAction(self.a_load_img)
        self.m_npk.addSeparator()
        self.m_npk.addAction(self.a_insert_npk)
        self.m_npk.addAction(self.a_replace_npk)
        self.m_npk.addAction(self.a_remove_npk)
        self.m_npk.addSeparator()
        self.m_npk.addAction(self.menuSound.menuAction())
        self.m_img.addAction(self.a_insert_img)
        self.m_img.addAction(self.a_replace_img)
        self.m_img.addAction(self.a_remove_img)
        self.menubar.addAction(self.m_app.menuAction())
        self.menubar.addAction(self.m_npk.menuAction())
        self.menubar.addAction(self.m_img.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OjoDnfExtractor"))
        self.m_app.setTitle(_translate("MainWindow", "文件"))
        self.m_npk.setTitle(_translate("MainWindow", "NPK"))
        self.menuSound.setTitle(_translate("MainWindow", "音效"))
        self.m_img.setTitle(_translate("MainWindow", "IMG"))
        self.a_open.setText(_translate("MainWindow", "打开..."))
        self.a_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.a_close.setText(_translate("MainWindow", "关闭"))
        self.a_close.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.a_insert_img.setText(_translate("MainWindow", "插入图像"))
        self.a_replace_img.setText(_translate("MainWindow", "替换图像"))
        self.a_remove_img.setText(_translate("MainWindow", "移除图像"))
        self.a_insert_npk.setText(_translate("MainWindow", "插入文件"))
        self.a_replace_npk.setText(_translate("MainWindow", "替换文件"))
        self.a_remove_npk.setText(_translate("MainWindow", "移除文件"))
        self.a_play.setText(_translate("MainWindow", "播放"))
        self.a_pause.setText(_translate("MainWindow", "暂停"))
        self.a_stop.setText(_translate("MainWindow", "停止"))
        self.a_loop.setText(_translate("MainWindow", "是否循环"))
        self.a_load_img.setText(_translate("MainWindow", "加载IMG文件"))
        self.a_load_img.setShortcut(_translate("MainWindow", "Ctrl+L"))

