# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(960, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_content = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_content.setObjectName("tw_content")
        self.gridLayout.addWidget(self.tw_content, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        self.m_main = QtWidgets.QMenu(self.menubar)
        self.m_main.setObjectName("m_main")
        self.m_extract_mode = QtWidgets.QMenu(self.m_main)
        self.m_extract_mode.setObjectName("m_extract_mode")
        self.m_npk = QtWidgets.QMenu(self.menubar)
        self.m_npk.setObjectName("m_npk")
        self.m_sound = QtWidgets.QMenu(self.m_npk)
        self.m_sound.setObjectName("m_sound")
        self.m_img = QtWidgets.QMenu(self.menubar)
        self.m_img.setObjectName("m_img")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.a_open = QtWidgets.QAction(MainWindow)
        self.a_open.setObjectName("a_open")
        self.a_close = QtWidgets.QAction(MainWindow)
        self.a_close.setObjectName("a_close")
        self.a_insert_img = QtWidgets.QAction(MainWindow)
        self.a_insert_img.setObjectName("a_insert_img")
        self.a_replace_img = QtWidgets.QAction(MainWindow)
        self.a_replace_img.setObjectName("a_replace_img")
        self.a_remove_img = QtWidgets.QAction(MainWindow)
        self.a_remove_img.setObjectName("a_remove_img")
        self.a_insert_npk = QtWidgets.QAction(MainWindow)
        self.a_insert_npk.setObjectName("a_insert_npk")
        self.a_replace_npk = QtWidgets.QAction(MainWindow)
        self.a_replace_npk.setObjectName("a_replace_npk")
        self.a_remove_npk = QtWidgets.QAction(MainWindow)
        self.a_remove_npk.setObjectName("a_remove_npk")
        self.a_sound_play = QtWidgets.QAction(MainWindow)
        self.a_sound_play.setObjectName("a_sound_play")
        self.a_sound_pause = QtWidgets.QAction(MainWindow)
        self.a_sound_pause.setObjectName("a_sound_pause")
        self.a_sound_stop = QtWidgets.QAction(MainWindow)
        self.a_sound_stop.setObjectName("a_sound_stop")
        self.a_sound_loop = QtWidgets.QAction(MainWindow)
        self.a_sound_loop.setCheckable(True)
        self.a_sound_loop.setObjectName("a_sound_loop")
        self.a_load_img = QtWidgets.QAction(MainWindow)
        self.a_load_img.setObjectName("a_load_img")
        self.a_extract_npk = QtWidgets.QAction(MainWindow)
        self.a_extract_npk.setObjectName("a_extract_npk")
        self.a_extract_img = QtWidgets.QAction(MainWindow)
        self.a_extract_img.setObjectName("a_extract_img")
        self.a_extract_all_npk = QtWidgets.QAction(MainWindow)
        self.a_extract_all_npk.setObjectName("a_extract_all_npk")
        self.a_extract_all_img = QtWidgets.QAction(MainWindow)
        self.a_extract_all_img.setObjectName("a_extract_all_img")
        self.a_extract_dir = QtWidgets.QAction(MainWindow)
        self.a_extract_dir.setObjectName("a_extract_dir")
        self.a_save = QtWidgets.QAction(MainWindow)
        self.a_save.setObjectName("a_save")
        self.a_extract_mode_raw = QtWidgets.QAction(MainWindow)
        self.a_extract_mode_raw.setCheckable(True)
        self.a_extract_mode_raw.setObjectName("a_extract_mode_raw")
        self.a_extract_mode_wodir = QtWidgets.QAction(MainWindow)
        self.a_extract_mode_wodir.setCheckable(True)
        self.a_extract_mode_wodir.setChecked(True)
        self.a_extract_mode_wodir.setObjectName("a_extract_mode_wodir")
        self.a_extract_map = QtWidgets.QAction(MainWindow)
        self.a_extract_map.setObjectName("a_extract_map")
        self.a_extract_all_map = QtWidgets.QAction(MainWindow)
        self.a_extract_all_map.setObjectName("a_extract_all_map")
        self.a_sound_single = QtWidgets.QAction(MainWindow)
        self.a_sound_single.setCheckable(True)
        self.a_sound_single.setChecked(True)
        self.a_sound_single.setObjectName("a_sound_single")
        self.a_extract_pos_info = QtWidgets.QAction(MainWindow)
        self.a_extract_pos_info.setObjectName("a_extract_pos_info")
        self.m_extract_mode.addAction(self.a_extract_mode_wodir)
        self.m_extract_mode.addAction(self.a_extract_mode_raw)
        self.m_main.addAction(self.a_open)
        self.m_main.addSeparator()
        self.m_main.addAction(self.a_extract_dir)
        self.m_main.addAction(self.m_extract_mode.menuAction())
        self.m_main.addSeparator()
        self.m_main.addAction(self.a_save)
        self.m_main.addSeparator()
        self.m_main.addAction(self.a_close)
        self.m_sound.addAction(self.a_sound_play)
        self.m_sound.addAction(self.a_sound_pause)
        self.m_sound.addAction(self.a_sound_stop)
        self.m_sound.addSeparator()
        self.m_sound.addAction(self.a_sound_loop)
        self.m_sound.addAction(self.a_sound_single)
        self.m_npk.addAction(self.a_load_img)
        self.m_npk.addSeparator()
        self.m_npk.addAction(self.a_extract_npk)
        self.m_npk.addAction(self.a_extract_all_npk)
        self.m_npk.addSeparator()
        self.m_npk.addAction(self.a_insert_npk)
        self.m_npk.addAction(self.a_replace_npk)
        self.m_npk.addAction(self.a_remove_npk)
        self.m_npk.addSeparator()
        self.m_npk.addAction(self.m_sound.menuAction())
        self.m_img.addAction(self.a_extract_img)
        self.m_img.addAction(self.a_extract_all_img)
        self.m_img.addSeparator()
        self.m_img.addAction(self.a_extract_map)
        self.m_img.addAction(self.a_extract_all_map)
        self.m_img.addSeparator()
        self.m_img.addAction(self.a_extract_pos_info)
        self.m_img.addSeparator()
        self.m_img.addAction(self.a_insert_img)
        self.m_img.addAction(self.a_replace_img)
        self.m_img.addAction(self.a_remove_img)
        self.menubar.addAction(self.m_main.menuAction())
        self.menubar.addAction(self.m_npk.menuAction())
        self.menubar.addAction(self.m_img.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OjoDnfExtractor"))
        self.m_main.setTitle(_translate("MainWindow", "主菜单"))
        self.m_extract_mode.setTitle(_translate("MainWindow", "提取模式"))
        self.m_npk.setTitle(_translate("MainWindow", "NPK"))
        self.m_sound.setTitle(_translate("MainWindow", "音效"))
        self.m_img.setTitle(_translate("MainWindow", "IMG"))
        self.a_open.setText(_translate("MainWindow", "打开..."))
        self.a_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.a_close.setText(_translate("MainWindow", "关闭"))
        self.a_close.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.a_insert_img.setText(_translate("MainWindow", "插入图像"))
        self.a_replace_img.setText(_translate("MainWindow", "替换图像"))
        self.a_remove_img.setText(_translate("MainWindow", "移除图像"))
        self.a_insert_npk.setText(_translate("MainWindow", "插入文件"))
        self.a_replace_npk.setText(_translate("MainWindow", "替换文件"))
        self.a_remove_npk.setText(_translate("MainWindow", "移除文件"))
        self.a_sound_play.setText(_translate("MainWindow", "播放"))
        self.a_sound_play.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.a_sound_pause.setText(_translate("MainWindow", "暂停"))
        self.a_sound_pause.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.a_sound_stop.setText(_translate("MainWindow", "停止"))
        self.a_sound_stop.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.a_sound_loop.setText(_translate("MainWindow", "是否循环"))
        self.a_load_img.setText(_translate("MainWindow", "加载IMG文件"))
        self.a_load_img.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.a_extract_npk.setText(_translate("MainWindow", "提取文件"))
        self.a_extract_npk.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.a_extract_img.setText(_translate("MainWindow", "提取图像"))
        self.a_extract_img.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.a_extract_all_npk.setText(_translate("MainWindow", "提取所有文件"))
        self.a_extract_all_npk.setShortcut(_translate("MainWindow", "Meta+Ctrl+Alt+S"))
        self.a_extract_all_img.setText(_translate("MainWindow", "提取所有图像"))
        self.a_extract_all_img.setShortcut(_translate("MainWindow", "Meta+Ctrl+Shift+S"))
        self.a_extract_dir.setText(_translate("MainWindow", "设置提取目录"))
        self.a_save.setText(_translate("MainWindow", "保存..."))
        self.a_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.a_extract_mode_raw.setText(_translate("MainWindow", "原始结构"))
        self.a_extract_mode_wodir.setText(_translate("MainWindow", "仅文件名"))
        self.a_extract_map.setText(_translate("MainWindow", "提取图像（map）"))
        self.a_extract_all_map.setText(_translate("MainWindow", "提取所有图像（map）"))
        self.a_sound_single.setText(_translate("MainWindow", "单实例播放"))
        self.a_extract_pos_info.setText(_translate("MainWindow", "提取偏移信息"))

